name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * *'  # Adjust the time as needed
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright Report Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Download Playwright Report Artifact
      uses: actions/download-artifact@v4
      with:
        name: playwright-report
        path: playwright-report

    - name: Compress Playwright Report
      run: |
        tar -czvf playwright-report.tar.gz playwright-report/

    - name: Send HTML report via email
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_APP_PASSWORD }}
        subject: "Playwright Test Results Summary"
        body: |
        Dear Team,  

        I hope this email finds you well.  

        Please find attached the latest **Playwright Test Execution Report** from our CI/CD pipeline. Below is a brief summary of the test results:  

        We have successfully executed the Playwright tests on the latest code. The report includes detailed information about the test execution, including the test results, screenshots, and other relevant details.

        Please review the attached report for more details. If you have any questions or need further assistance, please let me know.

        Best regards,
        Meghal
      
        to: "ermeghal1993@gmail.com"
        from: ${{ secrets.EMAIL_USER }}
        attachments: playwright-report.tar.gz