name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * *'  # Adjust the time as needed
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --reporter=allure

   - name: Install Allure
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Convert Allure Report to Single HTML
        run: |
          sudo apt-get install -y wkhtmltopdf
          wkhtmltopdf --enable-local-file-access allure-report/index.html allure-report.pdf


    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report.pdf
        retention-days: 7
        
    - name: Send Allure report via email
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_APP_PASSWORD }}
        subject: "Playwright Test Results Summary"
        body: |
          Playwright Test Results Summary from GitHub Actions
          
          Please find the attached Allure report.
          
          Note: This is an automated email from the CI/CD pipeline.
        to: "ermeghal1993@gmail.com"
        from: "${{ secrets.EMAIL_USER }}"
        attachments: allure-report.pdf